### ISSUE TITLE
Support for Fitting Covariance Matrix with Continuous Time Correlation Structures

### ISSUE THREAD

**Issue by imbhe** [gasparrini/mixmeta#1]
Thanks for creating such a great package! From what I gather in the documentation, the covariance matrix for repeated measures is treated as fixed (known beforehand).

Would it be possible to add functionality to fit the covariance matrix to the data, including also continuous time correlation structures?

If this is already supported, I’d love some pointers on how to set it up!

**Comment by gasparrini** [comment]
Hi Henrik, this extension has been in my mind for a some time. It is definitely possible, although it is logistically not straightforward as it requires passing additional information (specifically the time distance) externally from the model formula. It is feasible but it will require some planning and work.
However, your email has motivated me to put it back in the list. I hope I will manage to implement it at some point in the near future.

**Comment by imbhe** [comment]
Thanks Antonio, that would be great! Looking forward to seeing this update in the future. :)
